name: Test
on:
  push:
  pull_request:
  schedule:
    - cron: '45 20 * * *'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable
      - run: npm install
      - name: Wait for other builds to finish (if any)
        uses: softprops/turnstyle@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: make check
        env:
          MEDIAWIKI_USERNAME: ${{ secrets.MEDIAWIKI_USERNAME }}
          MEDIAWIKI_PASSWORD: ${{ secrets.MEDIAWIKI_PASSWORD }}
      - run: make all
